local path = ...
require(path .. ".Position")
require(path .. ".Rotation")
require(path .. ".Color")
require(path .. ".RenderRectangle")
require(path .. ".RenderCircle")
require(path .. ".ColliderRectangle")
require(path .. ".ColliderCircle")
require(path .. ".Physics")
require(path .. ".Sprite")